apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphiql
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: graphiql
      containers:
      - name: graphiql
        image: jasonblanchard/di-graphiql:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: graphiql-config
        # livenessProbe:
        #   httpGet:
        #     port: 8080
        #     path: /health
        # readinessProbe:
        #   httpGet:
        #     port: 8080
        #     path: /health
